# Generated by Django 2.2.4 on 2019-08-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0003_auto_20190830_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
