# Generated by Django 2.2.4 on 2019-09-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0007_auto_20190831_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name=''),
        ),
    ]
