# Generated by Django 2.2.4 on 2019-08-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(default='Enter a title::', max_length=30),
        ),
    ]
