# Generated by Django 2.2.4 on 2019-09-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='drafts',
            field=models.BooleanField(default=False),
        ),
    ]
