# Generated by Django 2.2.4 on 2019-09-05 13:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary_app', '0002_auto_20190905_1823'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Entry',
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
    ]
