# Generated by Django 2.2.4 on 2019-09-05 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0003_auto_20190905_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='drafts',
            new_name='trash',
        ),
    ]
