# Generated by Django 2.2.4 on 2019-09-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0006_auto_20190906_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='bio',
            field=models.TextField(default='', max_length=500),
        ),
    ]
