# Generated by Django 2.2.4 on 2019-08-31 11:36

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0006_auto_20190831_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name=''),
        ),
    ]
