# Generated by Django 2.2.4 on 2019-09-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0007_auto_20190910_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
