# Generated by Django 2.2.4 on 2019-09-03 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0010_auto_20190904_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='user',
        ),
    ]
