# Generated by Django 2.2.4 on 2019-09-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0011_remove_entry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='bio',
            field=models.TextField(max_length=500),
        ),
    ]
