# Generated by Django 2.2.4 on 2019-09-03 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0014_auto_20190904_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
